# Generated by Django 3.2.3 on 2021-05-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment_text', models.CharField(max_length=250)),
                ('reaction_type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike'), ('F', 'Favorite')], default='L', max_length=1)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.photo')),
            ],
        ),
    ]
