# Generated by Django 3.2.3 on 2021-05-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reaction_type',
            new_name='reaction',
        ),
    ]
